// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Database.Migrations
{
    [DbContext(typeof(InvoicingContext))]
    partial class InvoicingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Identifier")
                        .HasMaxLength(100);

                    b.Property<int?>("UpdatedByUserId");

                    b.HasKey("InvoiceId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Database.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InvoiceId");

                    b.Property<string>("Text")
                        .HasMaxLength(1000);

                    b.Property<int?>("UpdatedByUserId");

                    b.HasKey("NoteId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Identity")
                        .HasMaxLength(5);

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Database.Invoice", b =>
                {
                    b.HasOne("Database.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");
                });

            modelBuilder.Entity("Database.Note", b =>
                {
                    b.HasOne("Database.Invoice")
                        .WithMany("Notes")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("Database.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
